MiniProfiler/dotnet

StackExchange.Profiling.RavenDb/RavenMiniProfiler.cs

RequestResultArgs is formatted for every request even if the profiler is not started and before the check to see if MiniProfiler.Current is null. This formatting can mean quite a bit of JSON parsing. This is unnecessary work when the profiler has not been started.
This change moves this formatting until *after* the null check to see if the profiler has been started so that it does not format requests when it won't even use the result.

only format RequestResultArgs if the profiler has been started

---

StackExchange.Profiling.RavenDb/RavenMiniProfiler.cs
StackExchange.Profiling.RavenDb/StackExchange.Profiling.RavenDb.csproj

For issue #107.
I updated the `RavenMiniProfiler` implementation to be compatible with the new Async server client in Raven 3.0. This also maintains backwards compatibility with RavenDB 2.5 since the API is the same.
In Raven 2.5, all requests were synchronous so `HttpContext.Current` was accessible from the `LogRequest` event. However, in 3.0, everything is async-first, so more often than not, when `LogRequest` is thrown, it's on a different thread context which does not have access to `HttpContext.Current` so it could never find `MiniProfiler.Current`.
It's a little awkward but essentially this handles a different `ConfigureRequest` event which is thrown on every Raven request and is *before* any request is made so `HttpContext.Current` is available. We create a handler we pass that …

[Closes #107] Add RavenDB 3.0 compatibility

---

StackExchange.Profiling/MiniProfilerHandler.cs

There is a race condition where getting the list of profiler GUIDs would return a valid id but then loading the profiler by id it might not exist. This causes NullRefereneceExceptions. For example, we have our own Redis storage implementation where profilers automatically expire after a specified timeout.
So, depending on the storage, profilers might not exist by id and this protects against that.

Protect against NullReferenceExceptions when Load() returns a null profiler

---

StackExchange.Profiling/Storage/SqlServerStorage.cs

Short Version: other sql execution methods can be overridden, but this one cannot (e.g. Save).  As such derived code has to live with these limited select statements instead of having the opportunity to customize them.  To resolve this I propose changing the access modifier from 'private const' to 'protected'
Long Version:
Rational is:
1)  Would like to use NuGet package instead of building source code locally with each build
2)  Custom storage engine in its own project inherits from SqlServerStorage.
3)  Custom storage engine modifies the queries as the backing DB has been changed.
4)  Custom storage engine can't get access to 'private const SqlStatements'
5)  Can't X-Copy many/all the methods as the MiniProfiler class (used line 303) is defined as 'internal' (remember custom storage …

Change SqlStatements access modifier to protected

---

StackExchange.Profiling/MiniProfilerHandler.cs

If a non-authorized user visits a MiniProfiler results url (e.g. `http://app.com/mini-profiler-resources/results?id=<guid>`), they do *not* get a 401 status code. Having a 401 status code is what the documentation for `MiniProfiler.Settings.Results_Authorize` says it should return.

Make use of AuthorizeRequest to ensure a 401 status code for single profiler result

---

src/MiniProfiler.Shared/Helpers/IStopwatch.cs
tests/MiniProfiler.Tests/MiniProfilerConcurrencyTest.cs

New PR based on #140 targeting `v4` branch instead of `master`.
* Add MiniProfilerConcurrencyTest with 3 tests
* Step_WithParallelTasks_RealTime
* Step_WithParallelThreads_RealTime
* Step_WithParallelTasks_SimulatedTime
* Make internal type `StopwatchWrapper` visible to test project
The RealTime tests are a bit flaky due to not being deterministic. I have yet to find a good approach to do that kind of testing.

Add MiniProfilerConcurrencyTest to v4 branch for testing concurrent profiling with threads and tasks

---

src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs
src/MiniProfiler.Shared/ClientTimings.cs
src/MiniProfiler.Shared/SqlFormatters/SqlServerFormatter.cs
tests/MiniProfiler.Tests/Async/AsyncTests.cs
tests/MiniProfiler.Tests/lib/HaackHttpSimulator/HttpSimulator.cs

`string.StartsWith`/`EndsWith`/`IndexOf` do a culture-sensitive comparison by default, which could result in different behavior depending on the `CurrentCulture`. These comparisons should be `Ordinal`.

Specify StringComparison when calling string.StartsWith/EndsWith/IndexOf

---

src/MiniProfiler.Shared/ClientTimings.cs

`form.Keys` is already `ICollection<string>`, there's no need to cast.

Remove unnecessary `Cast<string>()`

---

src/MiniProfiler.Shared/ClientTimings.cs

Calls to `IndexOf(string, StringComparison.Ordinal)` when `string` is a single char can be replaced with `IndexOf(char`) for slightly improved performance. Also, in this case, the search can be conducted once instead of twice.

Use IndexOf(char) where appropriate

---

src/MiniProfiler.Shared/MiniProfiler.Settings.cs
src/MiniProfiler.Shared/SqlFormatters/SqlServerFormatter.cs

Explicit static cctors cause the C# compiler to not mark types as beforefieldinit, which means the JIT will add checks to each static method and instance constructors of the type to make sure that the static constructor was previously called. This can be avoided by removing explicit static constructors and initializing static fields inline.
See https://msdn.microsoft.com/en-us/library/ms182275.aspx for more info.

Remove explicit static constructors

---

src/MiniProfiler.Shared/Helpers/ExtensionMethods.cs
src/MiniProfiler.Shared/Helpers/StackTraceSnippet.cs
src/MiniProfiler.Shared/SqlFormatters/SqlServerFormatter.cs
tests/MiniProfiler.Tests/lib/HaackHttpSimulator/SimulatedHttpRequest.cs

Slightly cheaper and in some cases slightly simpler code (e.g. `'"'` vs. `"\""`). Though, I wouldn't expect much of a measurable difference in these cases.

Use StringBuilder.Append(char) for single chars

---

src/MiniProfiler.Shared/ui/includes.js

Wrap the client side fetch api to get profiler measurements when that is used rather than XHR

Wrap fetch for profiler

---

src/MiniProfiler.AspNetCore/MiniProfilerExtensions.cs
src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs

Bit uglier but sb.Replace was sky high on the execution
Before
After

Use cached StringBuilder rather than StringBuilder.Replace

---

src/MiniProfiler.Shared/MiniProfiler.ServerTiming.cs

GetServerTimingHeader should use milliseconds instead of seconds according to the [W3C specification](https://w3c.github.io/server-timing/#the-code-dfn-performanceservertiming-dfn-code-interface) ( [DOMHighResTimeStamp ](https://www.w3.org/TR/hr-time-2/#idl-def-domhighrestimestamp) to be exact).
This was a bug in the initial implementation in Chrome but was fixed in [Issue 704340](https://bugs.chromium.org/p/chromium/issues/detail?id=704340) and is in the current beta branch.
I also added proper NumberFormatInfo to the calls that turn the numbers into strings to account for different culture settings.

GetServerTimingHeader should use milliseconds instead of seconds

---

MiniProfiler.sln
build.ps1
src/MiniProfiler.Providers.MySql/MiniProfiler.Providers.MySql.csproj
src/MiniProfiler.Providers.MySql/MySqlStorage.cs

This adds an `IAsyncStorage` implementation that stores data in MySQL Server. It uses my [MySqlConnector library](https://github.com/mysql-net/MySqlConnector) so DB operations are truly async. It builds for `net451` and `netstandard1.5`.
Q: Do you want this code as part of the core MiniProfiler repository, or would you prefer it to be in its own repo and maintained separately?
90% of the code was ["derived from"](http://typicalprogrammer.com/introduction-to-abject-oriented-programming) `SqlServerStorage.cs`; if you are OK with the code being in this repo, I could refactor out that duplicated code into a new `StandardDatabaseStorageBase` abstract base class that contains the core DB logic and gets the SQL statements from its derived classes. (That could be done in this PR or a follow-up …

Add MySQL Server async storage backend

---

src/MiniProfiler.EF6/EFProfiledDbConnectionFactory.cs
src/MiniProfiler.EF6/EFProfiledDbProviderFactoryResolver.cs
src/MiniProfiler.EF6/EFProfiledInvariantNameResolver.cs
src/MiniProfiler.EF6/MiniProfilerEF6.cs
src/MiniProfiler.Shared/Data/ProfiledDbProviderFactory.cs

This pull request provides a number of enhancements to profiling EF6 based on our usage.
1. Cache the `EFProfiledDbProviderServices` instance.
Internally DbProviderServices is registered as a singleton. However when the service is "replaced" via `ReplaceService<>()`, the interception func is executed *every time* the service is resolved. We can cache the `EFProfiledDbProviderServices` instance (and anything else we want to replace) based on the type and key.
This should hopefully help keep the profiling overhead low.
2. The current implementation, which replaces `EFProfiledDbProviderServices`, only supports cached commands that cloned when needed by EF. The `Clone()` method creates a new `ProfiledDbCommand` with the current `MiniProfiler`. However for some queries, EF6 will use …

Entity Framework 6 Profiling Enhancements

---

src/MiniProfiler.EF6/MiniProfilerEF6.cs

EF may try to resolve dependencies with a null key for global singletons.
I'm annoyed at myself for not testing the refactoring of the original PR right way...

Fixing a bug caused by attempting to cache EF dependencies with a null key

---

src/MiniProfiler.Shared/Data/ProfiledDbConnection.cs
src/MiniProfiler.Shared/Internal/MiniProfilerExtensions.cs
src/MiniProfiler.Shared/MiniProfiler.Settings.cs
src/MiniProfiler.Shared/ui/includes.js

Introducing a new "CustomTimingExecuteTypesToIgnoreAsDuplicate" setting to
explicitly ignore duplicate custom timings based on its execute type.
By default it will ignore "Open" and "OpenAsync".

Ignore Duplicate based on ExecuteType (Fixes #194)

---

.vscode/launch.json
samples/Samples.AspNetCore/Views/Home/Index.LeftPanel.cshtml

It would be nice to have a link to the **result-index** page in the miniprofiler "widget" so I do not have to remember the link or put it in my own site.
Result looks like this: 
This PR also contains fix for vscode configurion (launch.json) and fixed link in AspNetCore sample project

Added link to results-index page 

---

src/MiniProfiler.Providers.MySql/MiniProfiler.Providers.MySql.csproj

This enables async database operations. (MySqlConnector has a fully async implementation; MySql.Data's async methods run synchronously on the caller's thread then return a completed Task.)
v0.30.0 is now strong-named, fixing the open issue with #188.

Switch (back) to MySqlConnector

---

samples/Samples.Mvc5.EFCore/Samples.Mvc5.EFCore.csproj
samples/Samples.Mvc5/Samples.Mvc5.csproj

This fixes the build on a fresh install of VS2017 Community

Avoid hard-coded path to roslyn compiler

---

docs/AspDotNetCore.md

It took me a while to figure out why following the instructions on https://miniprofiler.com/dotnet/AspDotNetCore did not work in my ASP.NET Core 2.0 MVC application.
Since the documentation said 
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache)
{
// ...existing configuration...
app.UseMiniProfiler();
}
```
I had added this line at the end of the Configure method.
Turns out that it needs to precede the call to app.UseMvc or it will not work.
"Not work" meaning:
The script tag is added to the html  
but the script which it tries to load is not available

Clarified asp.net core documentation

---

src/MiniProfiler.EF6/EFProfiledDbProviderServices.cs
src/MiniProfiler.EF6/MiniProfiler.EF6.csproj

EF 6.2.0 adds two new methods to `DbProviderServices` that must be overridden to correctly unwrap the `ProfiledDbConnection`.
This should resolve #243

Support for Entity Framework 6.2.0

---

src/MiniProfiler.Shared/SqlFormatters/InlineFormatter.cs

A parameter name or value that contained regex structures would make the regex break.
A part of a parameter value could also be identified as the name of a following parameter.
Fix #256

Fix #256 - Parameter name or value could break regex

---

src/MiniProfiler.Shared/ui/includes.js

Includes.js is using the window.chrome.loadTimes() API which has been marked as deprecated in the latest Chrome version and warns about it in the console.
``[Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: Paint Timing.``
This PR first checks if the new API is available (it is from Chrome 60) or it will fall back to the old deprecated one.
The new API doesn't support ``firstPaintAfterLoadTime`` though but it seems that like [Chrome never did](https://developers.google.com/web/updates/2017/12/chrome-loadtimes-deprecated#firstpaintafterloadtime) anyway. It does however add "first-contentful-paint" which is a way more interesting value to keep track of.

Update includes.js to prefer standardized timing APIs instead of deprecated ones

---

src/MiniProfiler.Shared/ui/includes.js

I think there was a small typo for "First Paint After Load Time" timing.

Fix firstPaintAfterLoadTime check

---

src/MiniProfiler.Shared/ui/includes.js

This can cause an endless loop, because `i` is overwritten.

`i` is already used in the function

---

src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

Currently, If I use URL as profiler name I get to see eg. `http%3A//localhost%3A53168/` in `results-index` page.
I have replaced javascript [escape](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) function, which is is unnecessarily strict, with HTML escape function.

Use HTML escape instead of javascript escape function

---

src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

Currently, when all _server_ timings are not trivial, the `show trivials` link is hidden even if there is trivial client timings

Display "show trivials" when any client timing is trivial

---

src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

If you don't already include jQuery in your page and use the `show-controls="true"` option you get the following error:
```
Uncaught TypeError: $ is not a function
at n.initControls (includes.min.js?v=4.0.0+g9bca957cdc:2)
....
```

Fix showControls when jQuery is not included

---

src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

I would like to be able to override init condition. Sometimes the *PopupView* is displayed earlier than all my client timings are finished.
eg.: 
In this example, I'd like to show *PopupView* after DotVVM is initialized. Sometimes it displays the *PopupView* before DotVVM initialization end. 
I'm not sure If I do something wrong or If I use it the way it was not intended to.

Added custom init condition

---

src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

I stumbled upon this problem after upgrading to latest version. CSS classes are being joined without any separators what brakes it a bit due to JS not being able to select right elements. I fixed it by adding default space prior to any new CSS class being added.

Fixed broken generation of CSS classes on mp-result element

---

src/MiniProfiler.Shared/MiniProfiler.cs

Fixes a couple spelling issues and ditches the [trailing whitespace](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TrailingWhitespaceVisualizer).

Fix spelling and casing of comments

---

src/MiniProfiler.AspNetCore/MiniProfilerOptions.cs

Which is the case when invoking the middleware from integration tests using `Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory<T>`. An example test is:
```
public class TelemetryFunctionalTests
{
public WebApplicationFactory<Program> Factory { get; }
public TelemetryFunctionalTests(WebApplicationFactory<Program> factory)
{
Factory = factory;
}
[Fact]
public async Task Get()
{
var client = Factory.CreateClient();
var telemetry = await Client.GetAsync("/Telemetry");
Assert.NotNull(telemetry);
}
}
```
This will currently throw a `NullReferenceException`  at https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.AspNetCore/MiniProfilerOptions.cs#L42

Fix NullReferenceException when RemoteIpAddress is null

---

src/MiniProfiler.AspNetCore.Mvc/ProfileScriptTagHelper.cs

Found an issue with where the initialization occurred when mocking out a test for issue #302.  This makes sure that the initialization doesn't occur on a child tag.

Initialize client timing at first parent tag

---

src/MiniProfiler.Shared/Data/ProfiledDbCommand.cs
tests/MiniProfiler.Tests/DbProfilerTests.cs

See: https://github.com/MiniProfiler/dotnet/issues/313

ProfiledDbCommand does not set connection for wrapped command

---

src/MiniProfiler.Shared/Data/ProfiledDbDataReader.cs
tests/MiniProfiler.Tests/DbProfilerTests.cs

I'm having issues with Npgsql and linq2db without calling Dispose on the actual reader.
It also fixes missing ReaderFinish call on netcoreapp1.1 if `Dispose` is being used to close the data reader.

Propagate Dispose from ProfiledDbDataReader

---

src/MiniProfiler.Providers.MongoDB/MongoDbStorage.cs
tests/MiniProfiler.Tests/Storage/MongoDbStorageTests.cs

Will still default to "MiniProfiler" when not set but otherwise will use the database as defined from the connection string.

MongoDB: Use database from connection string when set

---

src/MiniProfiler.Shared/MiniProfiler.IDbProfiler.cs

Lock was acquired for dictionary object, but not for _dbLocker and because of this, the dictionary was broken if methods ExecuteStart and ExecuteFinish were called from different threads.

Fix thread safe issue

---

azure-pipelines.yml
build.azureDevops.ps1
build.ps1

You can see the builds at https://dev.azure.com/agileguru/MiniProfiler/_build?definitionId=48&_a=summary
The build is triggered for every push to master and PR's targeting master.
The build process spins up 
- Redis
- MySQL
- PostgreSQL
- MongoDB 
- SQL Server (LocalDB)
The Build publishes Build Artifacts (not to be confused with Azure Artifacts) only for CI Builds (in master) and not for PR's.
**12 SQL Server Tests are skipped with below message**
`Couldn't test against: StackExchange.Profiling.Storage.SqlServerStorage\nThe type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
`

Add Support for Azure DevOps Builds

---

src/MiniProfiler.Shared/Data/ProfiledDbCommand.cs
src/MiniProfiler.Shared/Data/ProfiledDbDataReader.cs

Context: subclasses of `ProfiledDbCommand` may need to be aware of the `CommandBehavior` if they are providing a custom subclass of `ProfiledDbDataReader`, especially if they want to perform connection status tracking such as closure tracking.
Change: add `CommandBehavior behavior` as a parameter into the `CreateDbDataReader` method, that has not been released in RTM form yet.

CreateDbDataReader should expose the originally requested CommandBehavior

---

src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

Updated isoDate regex to make micro settings optional, fixing an possible issue with the lack of precision returned by MySQL.
Full details can be found in this issue #370 
This fix has been tested in isolation with a number of iso dates without micro seconds, the full repo hasn't been built or tested unfortunately.

Updated isoDate regex to make micro seconds optional

---

docs/AspDotNet.md

"AddViewProfiling" vs "AddViewPofiling". Looks like this spelling was corrected in the sample itself, but not in the docs.

Fixing typo in AspDotNet.md

---

docs/index.md

Addressing Issue #342
Looked at the ProcessRequest method in MiniProfilerHandler. I added it to the overview page as the routes don't changed based on framework and thus should be on a shared page. Further, creating a separate page seemed unwarranted for the amount of information.
Any other content that should be covered or any routes that I missed?

Exposed End Points Added to Documentation

---

docs/ConsoleDotNetCore.md

Adds a little bit of documentation that it is intentional to install the AspNetCore library instead of a Console library. Fixes #363 and references it in the documentation as I think the information of MiniProfiler outdating .NET Core is relevant

State why to install the AspNetCore package in .NET Core Console apps.

---

docs/HowTo/UpgradeFromV3.md
docs/NuGet.md
src/MiniProfiler.AspNetCore.Mvc/MiniProfiler.AspNetCore.Mvc.csproj
src/MiniProfiler.AspNetCore/MiniProfiler.AspNetCore.csproj
src/MiniProfiler.Providers.MongoDB/MiniProfiler.Providers.MongoDB.csproj
src/MiniProfiler.Providers.MySql/MiniProfiler.Providers.MySql.csproj
src/MiniProfiler.Providers.RavenDB/MiniProfiler.Providers.RavenDB.csproj
src/MiniProfiler.Providers.Redis/MiniProfiler.Providers.Redis.csproj
src/MiniProfiler.Providers.SqlServer/MiniProfiler.Providers.SqlServer.csproj
src/MiniProfiler.Providers.Sqlite/MiniProfiler.Providers.Sqlite.csproj
src/MiniProfiler.Shared/Data/ProfiledDbCommand.ICloneable.cs
src/MiniProfiler.Shared/Data/ProfiledDbCommand.cs
src/MiniProfiler.Shared/Data/ProfiledDbConnection.cs
src/MiniProfiler.Shared/Data/ProfiledDbDataAdapter.cs
src/MiniProfiler.Shared/Data/ProfiledDbDataReader.cs
src/MiniProfiler.Shared/Data/ProfiledDbProviderFactory.cs
src/MiniProfiler.Shared/Helpers/StackTraceSnippet.cs
src/MiniProfiler.Shared/Internal/IDataParameterExtensions.cs
src/MiniProfiler.Shared/MiniProfiler.Shared.csproj
src/MiniProfiler.Shared/MiniProfiler.cs
src/MiniProfiler.Shared/SqlFormatters/VerboseSqlServerFormatter.cs
tests/MiniProfiler.Tests.AspNetCore/MiniProfiler.Tests.AspNetCore.csproj

Going forward, only support `netstandard2.x` and above, but retain the `net461` builds to minimize binding pain and related issues.
This also lessens the dependency tree in the provider libs that were relaying on the NETStandard library due to implicit references.
This is a "maybe" PR to illustrate the cruft and dependencies we could drop.

Drop netstandard1.x support

---

samples/Samples.AspNetCore3/Samples.AspNetCore3.csproj
src/MiniProfiler.AspNetCore/MiniProfiler.AspNetCore.csproj
src/MiniProfiler.EF6/MiniProfiler.EF6.csproj
src/MiniProfiler.EFC7/MiniProfiler.EFC7.csproj
src/MiniProfiler.EntityFrameworkCore/MiniProfiler.EntityFrameworkCore.csproj
src/MiniProfiler.Mvc5/MiniProfiler.Mvc5.csproj
src/MiniProfiler.Providers.MongoDB/MiniProfiler.Providers.MongoDB.csproj
src/MiniProfiler.Providers.RavenDB/MiniProfiler.Providers.RavenDB.csproj
src/MiniProfiler.Providers.Redis/MiniProfiler.Providers.Redis.csproj
src/MiniProfiler.Providers.SqlServer/MiniProfiler.Providers.SqlServer.csproj
src/MiniProfiler.Providers.SqlServerCe/MiniProfiler.Providers.SqlServerCe.csproj
src/MiniProfiler.Shared/MiniProfiler.Shared.csproj
src/MiniProfiler/MiniProfiler.csproj

Removes all sorts of unused `.csproj` bits preparing for a 4.1.0 release.

Cleanup: trim down references in .csproj

---

appveyor.yml
azure-pipelines.yml
global.json
samples/Samples.AspNetCore3/Samples.AspNetCore3.csproj
src/MiniProfiler.AspNetCore/MiniProfiler.AspNetCore.csproj
version.json

This bumps versioning off pre-release packages for the .NET Core 3.0 release today.

Upgrade to 3.0 RTM packages and SDKs

---

Build.csproj
build.ps1

This side-steps build errors with Samples (excluding Mvc5) and builds packages much faster in one pass. Yeah baby!
This is using Traversal from https://github.com/microsoft/MSBuildSdks - attempted long ago with broken edge cases but looks good now!

Builds: Move to traversal SDK for cleanup

---

src/MiniProfiler.Providers.MySql/MiniProfiler.Providers.MySql.csproj

MySqlConnector 0.30.0 is quite old; it seems like it would be best to use the latest version, which has the latest bug fixes and performance enhancements.
(MySqlConnector 0.30.0 is the oldest strong-named version, so if you want to rely on the oldest possible version that is compatible with anything your users want to upgrade to, then I understand if you want to close this PR. I just think it would be best to install the latest good version by default.)

Update MySqlConnector to 0.60.1

---

src/MiniProfiler.Providers.MySql/MySqlStorage.cs
src/MiniProfiler.Providers.PostgreSql/PostgreSqlStorage.cs
src/MiniProfiler.Providers.SqlServer/SqlServerStorage.cs
src/MiniProfiler.Providers.Sqlite/SqliteStorage.cs

If the connection isn't already open, each call to `Execute(Async)` will open and close it, which is less efficient than opening it once and reusing the open connection.

Open the connection once

---

src/MiniProfiler.Shared/SqlFormatters/SqlServerFormatter.cs
tests/MiniProfiler.Tests/SqlFormatterTests.cs

Allows hiding parameter values if logging them in a sensitive issue. Feature request in #461.

Add SqlServerFormatter.IncludeParameterValues

---

docs/AspDotNetCore.md
docs/Releases.md
samples/Samples.AspNetCore3/Views/Shared/_Layout.cshtml
src/MiniProfiler.AspNetCore.Mvc/MiniProfilerScriptTagHelper.cs
src/MiniProfiler.Shared/Internal/Render.cs
src/MiniProfiler.Shared/MiniProfiler.Shared.csproj
src/MiniProfiler.Shared/RenderOptions.cs
tests/MiniProfiler.Tests/RenderTests.cs

Fix for #393, allows passing a nonce through the new `RenderOptions` API added in #451.
Also a minor optimization for async...we don't need that attribute value for any browser that'll support us today.

Add a nonce option and Render testing

---

src/MiniProfiler.AspNetCore.Mvc/MvcExtensions.cs
src/MiniProfiler.AspNetCore/MiniProfilerBuilderExtensions.cs
src/MiniProfiler.Shared/DiagnosticInitializer.cs

Proposed fix for #469, this follows the intended pattern a bit closer and also makes `DiagnosticListener` accessible.
cc @haacked

Shuffle DiagnosticListener to prevent double init

---

docs/AspDotNetCore.md
docs/Releases.md
samples/Samples.AspNetCore2/Startup.cs
samples/Samples.AspNetCore3/Startup.cs
src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs
src/MiniProfiler.AspNetCore/MiniProfilerOptions.cs
tests/MiniProfiler.Tests.AspNetCore/Middleware.cs
tests/MiniProfiler.Tests.AspNetCore/MiniProfiler.Tests.AspNetCore.csproj

Enhancement to support #417. Async auth is more and mor common, give it some love! Added tests, etc. to go with.
Also adds a bit more profiling in case init is ever slow.

.NET Core: Add ResultsAuthorizeAsync and ResultsListAuthorizeAsync

---

docs/Releases.md
src/MiniProfiler.AspNetCore.Mvc/MvcDiagnosticListener.cs
src/MiniProfiler.Shared/Internal/MiniProfilerBaseOptions.cs
src/MiniProfiler.Shared/MiniProfiler.cs
tests/MiniProfiler.Tests/InternalErrorTests.cs

Fix for #409 with some logging goodies.

Add Options.OnInternalError

---

src/MiniProfiler.Providers.RavenDB/RavenDbStorage.cs

This looked like a bug to me, assuming that the query works similarly to a regular `IQueryable`/`IEnumerable`.

Don't drop `Take` query instruction on the floor

---

samples/Samples.AspNetCore3/Pages/RazorPagesSample.cshtml
samples/Samples.AspNetCore3/Pages/_ViewImports.cshtml
samples/Samples.AspNetCore3/Pages/_ViewStart.cshtml
samples/Samples.AspNetCore3/Startup.cs
samples/Samples.AspNetCore3/Views/Shared/_Layout.cshtml
src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs

If you are using Razor Pages instead of controllers and views MiniProfiler shows all result names in the results list as `/`.  This is because `routeData.Values["controller"]` and `routeData.Values["action"]` are null.  
This change checks if `routeData.Values["pages"]` has a value and uses that for the MiniProfiler name if available.
I've also added a Razor Page to the Asp.Net Core 3 sample for testing

Use Razor Pages route value in MiniProfiler name

---

src/MiniProfiler.Shared/Internal/Render.cs
tests/MiniProfiler.Tests/RenderTests.cs

The latest release renders HTML with two endquotes for the data-position argument:
```html
<script src="..." data-position="Left"" data-scheme="Light" ></script> 
```

Remove double endquote in rendered HTML

---

samples/Samples.AspNetCore2/Samples.AspNetCore2.csproj
samples/Samples.ConsoleCore/Samples.ConsoleCore.csproj
src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs
src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts
tests/MiniProfiler.Tests.AspNetCore/MiniProfiler.Tests.AspNetCore.csproj
tests/MiniProfiler.Tests/MiniProfiler.Tests.csproj

We can go simple here because there is no security issue, it's just a CSS style we're storing. Basically we're just remember whether it's shown or hidden across page views - this take precedence over settings from the server for default visibility.
Note: I'm just `try`/`catch`ing around Mobile Safari's shenanigans since we are only seeing if this works and using it in _one_ case. The 99% case here should be smooth sailing, and in the case it doesn't work: there's nothing to do here.

JS: Remember visibility via localStorage

---

src/MiniProfiler.Providers.MySql/MiniProfiler.Providers.MySql.csproj
src/MiniProfiler.Providers.MySql/MySqlStorage.cs

MySqlConnector 1.0 introduces a breaking change by changing the namespace: https://github.com/mysql-net/MySqlConnector/issues/824
This updates the dependency and fixes the code.

Update MySqlConnector to 1.0

---

src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

Fixes the null reference error when customtiming object does not have any timings but the key exists:
https://twitter.com/andersaberg/status/1285660570608377856
Made the change in the browser, but I hope the TS syntax was correct.

Empty array instead of null when handling customtimings

---

samples/Samples.AspNetCore3/Startup.cs
samples/Samples.AspNetCore3/Views/Shared/Index.LeftPanel.cshtml
src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs

Enhancement requested in #514 
Two example routes added to Sample App for 3.0 to highlight explicit vs. implicit endpoint naming.
Also adds a fix in the sample project to correctly configure areas with endpoint routing that can be removed if needed. As is the area route link in the Sample resulted in a 404 for me.

Add check to use Endpoint.DisplayName over base url when naming profiler

---

src/MiniProfiler.Shared/DiagnosticInitializer.cs

I'm not sure how this happens _exactly_, but we can avoid the impact with some lightweight locking.

Fix for #522

---

src/MiniProfiler.Shared/Internal/MiniProfilerBaseOptions.cs

Fixes typo in XML comment for `MiniProfilerBaseOptions.TrackConnectionOpenClose`

Fix typo in XML comment

---

src/MiniProfiler.Providers.MongoDB/MongoDbStorage.cs
tests/MiniProfiler.Tests/Storage/MongoDbStorageTests.cs

Fixes #542 
Part of me wanted to add a test to assert the optional collection name but with how the code is structured currently, it felt a little over the top.

MongoDB: Allow custom collection names for profiling results

---

benchmarks/MiniProfiler.Benchmarks/Benchmarks/InlineFormatterBenchmarks.cs
benchmarks/MiniProfiler.Benchmarks/Configs.cs
benchmarks/MiniProfiler.Benchmarks/MiniProfiler.Benchmarks.csproj
src/MiniProfiler.Shared/SqlFormatters/InlineFormatter.cs

This PR updates BenchmarkDotNet, adds a benchmark for `InlineFormatter.FormatSql`, and optimizes that method.
When trying to pin down performance issues with MiniProfiler it was reporting a step as taking >60 seconds when that step just wrapped an SQL command that it reported as taking ~1.5 seconds. The SQL was run through Dapper and had a huge `IN ()` statement using a list parameter with ~14k items. After some investigation I found out that it only happened when there was an active MiniProfiler session and that it wouldn't happen if I put the values directly in the query instead of passing them as a parameter. Eventually I ended up at `InlineFormatter.FormatSql`.
When benchmarking it I found that performance was dramatically worse when a parameter object's name property lacks a DB param …

Optimize InlineFormatter

---

docs/Releases.md
src/MiniProfiler.Shared/SqlFormatters/InlineFormatter.cs
src/MiniProfiler.Shared/SqlFormatters/SqlFormatterExtensions.cs
src/MiniProfiler.Shared/SqlFormatters/SqlServerFormatter.cs
tests/MiniProfiler.Tests/SqlFormatterTests.cs

Fixes #539 
Default is enabled, like the existing GetReadableCommand logic.

InlineFormatter: Optionally support spacing around commas

---

docs/Releases.md
src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

This propagates the `nonce` attribute to the generated <link> element as it should for proper CSP handling.

Fix for #560 - propagate  nonce to <link>

---

src/MiniProfiler.AspNetCore.Mvc/MvcDiagnosticListener.cs

Meant to do this a while ago - stop generating strings for repeated things. We have a finite amount of combinations here, so let's use that to our advantage.
Overall, we most often have a pair of one label that doesn't change at all and a second string within a finite set. Because of this, we can cache the tuple or 2 => string conversion and not allocate to gen 0 per step. Since the conversion of source => final string on the second half only happens once, we can also prettify it a bit without paying the cost each time.

Optimize MVC diagnostic listener

---

src/MiniProfiler.Shared/MiniProfiler.IDbProfiler.cs

We are getting the following null reference exceptions:
```
System.NullReferenceException
HResult=0x80004003
Message=Object reference not set to an instance of an object.
Source=MiniProfiler.Shared
StackTrace:
at StackExchange.Profiling.MiniProfiler.StackExchange.Profiling.Data.IDbProfiler.ExecuteFinish(IDbCommand profiledDbCommand, SqlExecuteType executeType, DbDataReader reader) in C:\projects\dotnet\src\MiniProfiler.Shared\MiniProfiler.IDbProfiler.cs:line 75
at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 297
at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2813
at …
```

IDbProfiler not adding to _inProgress if timing is null

---

src/MiniProfiler.Shared/Internal/Render.cs

This was partially fixed in #497 but not for the other overload of this function.

Fix #592 double quotes on data-position attribute

---

benchmarks/MiniProfiler.Benchmarks/Benchmarks/CustomTimingBenchmarks.cs
benchmarks/MiniProfiler.Benchmarks/MiniProfiler.Benchmarks.csproj
benchmarks/MiniProfiler.Benchmarks/Program.cs
src/MiniProfiler.Shared/Helpers/StackTraceSnippet.cs

TL;DR: Cache the names of `System.Reflection.Assembly` and `System.Reflection.Module` instances in a static dictionary as they are non-trivially recomputed on every read of the property. This reduces allocations by ~70% and doubles speed when instantiating `CustomTiming` with stack traces (the default behaviour).
---
Instantiating `CustomTiming` with 'normal' parameters allocated a surprisingly large amount in the benchmarks. A chunk of it is from calling `new StackTrace().GetFrames();` which I don't think we can do anything about in a reasonable way.. but most was from reflection, which is almost completely mitigated by these changes.
The problem is that `Assembly.GetName().Name` and `Module.Name` don't persist the resulting value. You can see that …

Optimise StackTraceSnippet.Get

---

docs/Releases.md
samples/Samples.AspNet/Helpers/NonceService.cs
samples/Samples.AspNet/Pages/RazorPagesSample.cshtml
samples/Samples.AspNet/Startup.cs
samples/Samples.AspNet/Views/Shared/Index.cshtml
samples/Samples.AspNet/Views/Shared/_Layout.cshtml
src/MiniProfiler.AspNetCore/MiniProfilerExtensions.cs
src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs
src/MiniProfiler.Shared/Internal/MiniProfilerBaseOptions.cs
src/MiniProfiler.Shared/Internal/Render.cs
src/MiniProfiler.Shared/MiniProfiler.Shared.csproj
src/MiniProfiler.Shared/ui/includes.css
src/MiniProfiler.Shared/ui/includes.less
src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts
src/MiniProfiler/MiniProfilerHandler.cs
tests/MiniProfiler.Tests/RenderTests.cs

Dear MiniProfiler team,
Thank you for making this project easy to build and fork. 
With this PR MiniProfiler will run under a strict CSP that disallows inline styles and scripts (by using nonce) with zero errors.
It accomplish this by putting dynamically generated style tag values as data attributes, and then later after appending the miniprofiler html, it queries for them and manipulates the style object on Element directly, thus eliminating the need for inline style.

Eliminate the use of inline styles, making it compatible with strict CSP for style.

---

docs/Releases.md
src/MiniProfiler.Shared/Internal/Render.cs

Fixing #652, thanks for the report!

Fix #652 - respect PopupDecimalPlaces in all cases

---

docs/AspDotNetCore.md

Fix method name of async `ResultsListAuthorizeAsync` method in documentation.

Fix method name of async ResultsListAuthorizeAsync method in documentation.

---

samples/Samples.ConsoleCore/Program.cs

In this example we don't have a result for `TestAsync() ` 
since method is async the result of **MiniProfiler.Current is null** in main method so we have to print result inside TestAsync Method

Fix problem with showing async method profile

---

src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

Allow the client code to provide additional headers for custom implementations.
Specifically the goal for us is to be able to include authentication using a bearer token, but this solution should cover other custom cases as well.

Allow additional headers
