MiniProfiler/dotnet

StackExchange.Profiling/MiniProfiler.Settings.cs
StackExchange.Profiling/MiniProfilerHandler.cs

This setting should allow to disable the compression so users still have the options to user their own compression system.

Add a setting to enable compression, default true

---

src/MiniProfiler.Shared/MiniProfiler.Settings.cs
src/MiniProfiler.Shared/MiniProfiler.Shared.csproj
src/MiniProfiler.Shared/MiniProfiler.cs
src/MiniProfiler.Shared/SqlTiming.cs
src/MiniProfiler/MiniProfiler.csproj

- Had to comment out some lines that appear to be in the middle of a refactoring effort

Shared now builds

---

src/MiniProfiler/ProfileProviders/WebRequestProfilerProvider.cs
tests/MiniProfiler.Tests/lib/HaackHttpSimulator/HttpSimulator.cs

Path comparisons should be Ordinal

Use StringComparison.OrdinalIgnoreCase instead of InvariantCultureIgnoreCase

---

src/MiniProfiler/ProfileProviders/WebRequestProfilerProvider.cs

Fixes #171 
Implementing a slightly better, albeit relatively naive, GetAppRelativePath() which will actually include all of the path information (minus query string) after any "file extension".
While this causes in an string allocation, it's no worse than what `AppRelativeCurrentExecutionFilePath` is doing under the hood.
Also, a little bit of cleanup such as accessing Request.Path just once, and accessing Request.Url only when we need it.

Support ignoring request paths matching after a file extensions

---

src/MiniProfiler.Shared/MiniProfiler.cs

For @jdaigle to review - we've got some IIS eventing `AsyncLocal` issues aiming to be solved, see discussion in #173 for details.

Proposed fix for #173

---

src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs

Fix: Response Content-Length mismatch

---

docs/AspDotNet.md

Docs: Fix syntax errors and remove trailing whitespace

---

src/MiniProfiler.Shared/ui/includes.js

These names are handled by `SentenceCase` and look better in the UI if they are set first with lower camel case.

Change paint event names to have lower camel case

---

MiniProfiler.sln
appveyor.yml
src/MiniProfiler.Providers.MongoDB/MiniProfiler.Providers.MongoDB.csproj
src/MiniProfiler.Providers.MongoDB/MongoDbStorage.cs
tests/MiniProfiler.Tests/Helpers/TestConfig.cs
tests/MiniProfiler.Tests/MiniProfiler.Tests.csproj
tests/MiniProfiler.Tests/Storage/MongoDbStorageTests.cs

Hi Nick,
I have been working in a new implementation for the MongoDB provider. I tried to follow the way that it was implemented last version, in v3. I have used the last MongoDB nuget up to date (v2.5.0). Integration tests passed.
Hope it helps!
https://github.com/MiniProfiler/dotnet/issues/125

Feature Mongodb provider

---

src/MiniProfiler.Providers.MongoDB/MongoDbStorage.cs
tests/MiniProfiler.Tests/Storage/MongoDbStorageTests.cs

Hi, @NickCraver, i saw your tweet and I have some ideas
1. Only 1 colleciton
2. No poco
3. Manual mapping
4. Fix bug https://github.com/MiniProfiler/dotnet/blob/c32b23097331666637b846d6b83389363be29cd5/src/MiniProfiler.Providers.MongoDB/MongoDbStorage.cs#L94 to Less Than 
5. Add WithIndexCreation method

Simplify mongo db provider

---

src/MiniProfiler.Shared/SqlFormatters/SqlServerFormatter.cs
tests/MiniProfiler.Tests/SqlFormatterTests.cs

Add SQL formatting for numeric types of Double, Single, Currency, and Decimal.

SQL formatting for numeric types

---

src/MiniProfiler.Shared/Internal/IDataParameterExtensions.cs
src/MiniProfiler.Shared/SqlFormatters/SqlServerFormatter.cs
tests/MiniProfiler.Tests/SqlFormatterTests.cs

Add in translations for missing DbType enumeration values.

Map missing data types in SQL formatter

---

azure-pipelines.yml
build.azureDevops.ps1

PR so we get builds during this...let's try to make Azure Pipelines service containers work.

Build: Service containers

---

.gitignore
appveyor.yml
azure-pipelines.yml
global.json
samples/Samples.AspNetCore3/Samples.AspNetCore3.csproj
src/MiniProfiler.AspNetCore/MiniProfiler.AspNetCore.csproj

Updates the .NET Core SDKs and refs to preview 9 so we can get a NuGet preview out there.

.NET Core 3.0 Preview 9 Updates

---

src/Directory.Build.props

Tidying up to latest package specs and builder packages.

Update package license data and build packages

---

Readme.md

- Fixes http:// links to https://
- Add .NET Foundation info
- Adds a code of conduct link to .NET Foundation's
- Adds more build details
- Updates to Visual Studio 2019

Update README to latest info

---

samples/Directory.Build.props
samples/Samples.AspNetCore2/Samples.AspNetCore2.csproj
samples/Samples.AspNetCore2/Views/Shared/Index.RightPanel.cshtml
samples/Samples.AspNetCore2/Views/Shared/Index.cshtml
samples/Samples.AspNetCore2/Views/Shared/Nested.cshtml
samples/Samples.AspNetCore2/Views/Shared/Tree.cshtml
samples/Samples.ConsoleCore/Samples.ConsoleCore.csproj
tests/Directory.Build.props
tests/MiniProfiler.Tests.AspNet/MiniProfiler.Tests.AspNet.csproj
tests/MiniProfiler.Tests.AspNetCore/MiniProfiler.Tests.AspNetCore.csproj
tests/MiniProfiler.Tests/Helpers/TestConfig.cs
tests/MiniProfiler.Tests/Helpers/TestExtensions.cs
tests/MiniProfiler.Tests/MiniProfiler.Tests.csproj
tests/MiniProfiler.Tests/Storage/MongoDbStorageTests.cs
tests/MiniProfiler.Tests/Storage/MySqlStorageTests.cs
tests/MiniProfiler.Tests/Storage/PostgreSqlStorageTests.cs
tests/MiniProfiler.Tests/Storage/RedisStorageTests.cs
tests/MiniProfiler.Tests/Storage/SqlServerCeStorageTests.cs
tests/MiniProfiler.Tests/Storage/SqlServerStorageTests.cs
tests/MiniProfiler.Tests/Storage/SqliteStorageTests.cs

This is all of the build tweaks for Linux in general that aren't part of Actions, just needed doing to help debug, etc.

Pre-merge for #416

---

samples/Samples.AspNetCore2/Startup.cs
samples/Samples.AspNetCore3/Properties/launchSettings.json
samples/Samples.AspNetCore3/Startup.cs
src/MiniProfiler.AspNetCore.Mvc/MvcExtensions.cs

A better solution to #437, since it's safe to re-run (it's a try add).

Always register IMemoryCache

---

.github/workflows/main.yml
Build.csproj
Directory.Build.props
build.ps1
samples/Directory.Build.props
src/Directory.Build.props
tests/Directory.Build.props
tests/Directory.Build.targets
tests/MiniProfiler.Tests.AspNet/MiniProfiler.Tests.AspNet.csproj
tests/MiniProfiler.Tests.AspNetCore/MiniProfiler.Tests.AspNetCore.csproj
tests/MiniProfiler.Tests/MiniProfiler.Tests.csproj

This is just simplifying and DRYing up builds a bit more than current.

Builds: simplify!

---

src/MiniProfiler.Shared/Internal/ExtensionMethods.cs

Apps messing with global date shenanigans are hosing the JavaScript here - make sure we output what the client experts.

Fix for #459

---

Directory.Build.props
src/Directory.Build.props
tests/MiniProfiler.Tests.AspNetCore/Middleware.cs

Upgrades packaging to latest bits and off previews.

Upgrade build tooling

---

docs/Releases.md
src/MiniProfiler.Providers.Redis/MiniProfiler.Providers.Redis.csproj

Taking the major lib update here in the 4.2.x release.

MiniProfiler.Providers.Redis = update to 2.1.30

---

docs/AspDotNet.md
docs/AspDotNetCore.md

Docs: add route info

---

global.json
src/MiniProfiler.AspNetCore.Mvc/MvcDiagnosticListener.cs

Testing in Stack Overflow, we see a null ref chance with the Stack - slim it down and link list the prev step for unwind fallbacks.

Fix AsyncLocal<T> and fix null ref in completion

---

src/MiniProfiler.Providers.MySql/MySqlStorage.cs

Instead of relying on the defaults, ensure that MySqlConnector string options are set to the values that this library requires to (de)serialize data correctly:
* Force `DateTime` to be stored in UTC and returned as `DateTime` (not `MySqlDateTime`)
* Store `Guid` as `CHAR(36)`
* Disable user variables and connection reset (optimisation that's safe because no variables or temporary tables are used)
* Store `bool` as `TINYINT(1)`
This improves robustness if the user passes in a connection string with overridden defaults (e.g., if MySQL is being used by the application for other purposes and needs a different configuration).

Explicitly set MySQL connection string options

---

src/MiniProfiler.Shared/Data/ProfiledDbCommand.cs
tests/MiniProfiler.Tests/DbProfilerTests.cs

This adds a path for always wrapping readers so that anyone inheriting from `ProfiledDbDataReader` and overriding functionality can depend on that by also overriding this new property to `true`.

Add ProfiledDbCommand.AlwaysWrapReaders

---

docs/AspDotNet.md

I found the installation instructions confusing, and [this issue](https://github.com/MiniProfiler/dotnet/issues/350) provided some insights. I think it would be valuable to make these instructions part of the documentation.

Instructions on actually rendering the mini profiler

---

samples/Samples.AspNet5/Views/Shared/Components/ComponentTest/ComponentTest.cs
samples/Samples.AspNet5/Views/Shared/Nested.cshtml
src/MiniProfiler.AspNetCore.Mvc/MvcDiagnosticListener.cs

Fixes #571, missed this somehow in the initial diagnostic source bits.

Add ViewComponents to view profiling

---

src/MiniProfiler.Shared/MiniProfiler.cs

Resolves the high performance stopwatch issue.

Fix for #597

---

src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts

Fixes both #653 and #659 by updating the UI to work with the recent-trace-first sorting introduced in #550

Fix #653, #659 - Fix UI to work with most recent first
